# Generated by Django 3.2.13 on 2022-10-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredientinrecipe_unique_ingredient_in_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/', verbose_name='Image'),
        ),
    ]
